"""discovery_api.media 单元测试：payload 构造、streamAssist 流解析、文件下载。"""

import json

import httpx
import pytest
from fastapi import HTTPException

from discovery_api import media

SESSION = (
    "projects/test-project/locations/global/collections/default_collection"
    "/engines/test-engine/sessions/4472094446372259871"
)


def _chunk(replies: list[dict], state: str | None = None) -> dict:
    obj: dict = {
        "answer": {"replies": replies},
        "sessionInfo": {"session": SESSION, "queryId": "q1"},
    }
    if state:
        obj["answer"]["state"] = state
    return obj


def _file_reply(file_id: str, mime: str) -> dict:
    return {
        "groundedContent": {
            "content": {"role": "model", "file": {"fileId": file_id, "mimeType": mime}}
        }
    }


def _text_reply(text: str) -> dict:
    return {"groundedContent": {"content": {"role": "model", "text": text}}}


# ---------- payload ----------


def test_build_payload_image():
    p = media.build_media_payload("a red bicycle", "image")
    assert p["query"] == {"text": "a red bicycle"}
    assert p["toolsSpec"] == {"imageGenerationSpec": {}}


def test_build_payload_video():
    p = media.build_media_payload("ocean waves", "video")
    assert p["toolsSpec"] == {"videoGenerationSpec": {}}


def test_build_payload_rejects_unknown_kind():
    with pytest.raises(ValueError):
        media.build_media_payload("x", "audio")  # type: ignore[arg-type]


# ---------- generate_media ----------


def _client_returning(body: str | bytes, status: int = 200) -> httpx.AsyncClient:
    def handler(request: httpx.Request) -> httpx.Response:
        assert request.url.path.endswith(":streamAssist")
        assert request.headers["authorization"] == "Bearer tok"
        assert request.headers["x-goog-user-project"] == "test-project"
        return httpx.Response(status, content=body, headers={"content-type": "application/json"})

    return httpx.AsyncClient(transport=httpx.MockTransport(handler))


async def test_generate_image_returns_file_ref():
    stream = json.dumps(
        [
            _chunk(
                [_file_reply("f-1", "image/png"), _text_reply("Image generated by Nano Banana 2.")]
            ),
            _chunk([], state="SUCCEEDED"),
        ]
    )
    async with _client_returning(stream) as client:
        result = await media.generate_media(client, "a red bicycle", "image", "tok")
    assert result.session == SESSION
    assert result.session_id == "4472094446372259871"
    assert result.files == [media.MediaFile(file_id="f-1", mime_type="image/png")]
    assert result.text == "Image generated by Nano Banana 2."


async def test_generate_video_collects_file_after_progress_text():
    stream = json.dumps(
        [
            _chunk([_text_reply("**Generating video. This may take a few minutes...**\n")]),
            _chunk([_file_reply("v-1", "video/mp4")]),
            _chunk([], state="SUCCEEDED"),
        ]
    )
    async with _client_returning(stream) as client:
        result = await media.generate_media(client, "ocean waves", "video", "tok")
    assert result.files == [media.MediaFile(file_id="v-1", mime_type="video/mp4")]
    assert "Generating video" in result.text


async def test_generate_media_upstream_error_maps_status():
    async with _client_returning('{"error":{"code":403,"message":"denied"}}', status=403) as client:
        with pytest.raises(HTTPException) as ei:
            await media.generate_media(client, "x", "image", "tok")
    assert ei.value.status_code == 403
    assert "denied" in str(ei.value.detail)


async def test_generate_media_no_file_is_502():
    stream = json.dumps([_chunk([_text_reply("I cannot do that.")], state="SUCCEEDED")])
    async with _client_returning(stream) as client:
        with pytest.raises(HTTPException) as ei:
            await media.generate_media(client, "x", "image", "tok")
    assert ei.value.status_code == 502
    assert "I cannot do that." in str(ei.value.detail)


# ---------- download ----------


def test_download_url_uses_session_resource_name():
    url = media.download_url(SESSION, "f-1")
    assert url.startswith("https://discoveryengine.googleapis.com/v1alpha/")
    assert url.endswith(f"{SESSION}:downloadFile?fileId=f-1&alt=media")


async def test_download_session_file_follows_redirect():
    calls: list[str] = []

    def handler(request: httpx.Request) -> httpx.Response:
        calls.append(request.url.path)
        assert request.headers["authorization"] == "Bearer tok"
        if request.url.path.startswith("/download/"):
            return httpx.Response(200, content=b"\x89PNG...", headers={"content-type": "image/png"})
        return httpx.Response(
            302,
            headers={
                "location": "https://discoveryengine.googleapis.com/download"
                + request.url.path
                + "?"
                + request.url.query.decode()
            },
        )

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as client:
        data, mime = await media.download_session_file(client, SESSION, "f-1", "tok")
    assert data == b"\x89PNG..."
    assert mime == "image/png"
    assert len(calls) == 2 and calls[1].startswith("/download/v1alpha/")


async def test_download_session_file_error():
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(404, json={"error": {"message": "nope"}})

    async with httpx.AsyncClient(transport=httpx.MockTransport(handler)) as client:
        with pytest.raises(HTTPException) as ei:
            await media.download_session_file(client, SESSION, "f-1", "tok")
    assert ei.value.status_code == 404


def test_session_resource_name_from_id():
    assert media.session_resource_name("42") == (
        "projects/test-project/locations/global/collections/default_collection"
        "/engines/test-engine/sessions/42"
    )
