"""Gemini Enterprise 生图 / 生视频。

复用 :streamAssist，生成物以 fileId 返回，再经 :downloadFile 拉取。

实测（2026-09）：
- imageGenerationSpec / videoGenerationSpec 均为空 message，无可调参数，只能靠 prompt。
- 生成物不走 inlineData，而是 reply.groundedContent.content.file = {fileId, mimeType}。
- 下载端点未在公开文档列出：GET v1alpha/{session}:downloadFile?fileId=..&alt=media，服务端 302 到
  /download/v1alpha/...，需跟随重定向并带同一 Bearer token。
"""

import logging
from dataclasses import dataclass, field
from typing import Any, Literal

import httpx
from fastapi import HTTPException

from .agent_search import _assist_url, _iter_json_objects
from .config import settings

logger = logging.getLogger(__name__)

MediaKind = Literal["image", "video"]

_TOOL_SPEC: dict[str, str] = {
    "image": "imageGenerationSpec",
    "video": "videoGenerationSpec",
}

# 实测生图 ~36s、生视频 ~90s；留足余量，避免 httpx 默认 60s 超时截断视频流
MEDIA_TIMEOUT = httpx.Timeout(600.0, connect=30.0)
DOWNLOAD_TIMEOUT = httpx.Timeout(300.0, connect=30.0)


@dataclass(frozen=True)
class MediaFile:
    file_id: str
    mime_type: str


@dataclass(frozen=True)
class MediaResult:
    session: str  # 完整 session 资源名，下载时必需
    files: list[MediaFile] = field(default_factory=list)
    text: str = ""  # 伴随文本，例如 "Image generated by Nano Banana 2."

    @property
    def session_id(self) -> str:
        return self.session.rsplit("/", 1)[-1]


def build_media_payload(prompt: str, kind: MediaKind) -> dict[str, Any]:
    spec = _TOOL_SPEC.get(kind)
    if spec is None:
        raise ValueError(f"Unsupported media kind: {kind!r}")
    payload: dict[str, Any] = {"query": {"text": prompt}, "toolsSpec": {spec: {}}}
    if settings.agent_search_model_version:
        payload["generationSpec"] = {"modelId": settings.agent_search_model_version}
    return payload


def session_resource_name(session_id: str) -> str:
    return (
        f"projects/{settings.gcp_project_id}/locations/{settings.discovery_location}"
        f"/collections/default_collection/engines/{settings.agent_search_engine}"
        f"/sessions/{session_id}"
    )


def download_url(session: str, file_id: str) -> str:
    return (
        f"https://discoveryengine.googleapis.com/v1alpha/{session}:downloadFile"
        f"?fileId={file_id}&alt=media"
    )


def _headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "X-Goog-User-Project": settings.gcp_project_id,
    }


def _collect(answer: dict[str, Any], files: list[MediaFile], texts: list[str]) -> None:
    for reply in answer.get("replies") or []:
        content = (reply.get("groundedContent") or {}).get("content") or {}
        if content.get("thought"):
            continue
        if t := content.get("text"):
            texts.append(t)
        f = content.get("file") or {}
        if fid := f.get("fileId"):
            mf = MediaFile(file_id=fid, mime_type=f.get("mimeType", "application/octet-stream"))
            if mf not in files:
                files.append(mf)


async def generate_media(
    client: httpx.AsyncClient, prompt: str, kind: MediaKind, token: str
) -> MediaResult:
    """调用 GE :streamAssist 生成图片/视频，返回 fileId 列表（不下载内容）。"""
    payload = build_media_payload(prompt, kind)
    files: list[MediaFile] = []
    texts: list[str] = []
    session = ""

    async with client.stream(
        "POST",
        _assist_url(stream=True),
        headers=_headers(token),
        json=payload,
        timeout=MEDIA_TIMEOUT,
    ) as r:
        if r.status_code != 200:
            err = (await r.aread()).decode(errors="replace")
            logger.error("GE Assist API %s (%s generation): %s", r.status_code, kind, err)
            raise HTTPException(status_code=r.status_code, detail=f"GE Assist API error: {err}")
        async for obj in _iter_json_objects(r):
            if s := (obj.get("sessionInfo") or {}).get("session"):
                session = s
            _collect(obj.get("answer") or {}, files, texts)

    text = "".join(texts).strip()
    if not files:
        logger.warning("GE %s generation returned no file. text=%r", kind, text[:300])
        raise HTTPException(
            status_code=502,
            detail=(
                f"Gemini Enterprise returned no {kind} file. "
                f"Assistant said: {text or '(empty)'}"
            ),
        )
    logger.info(
        "GE %s generation ok: session=%s files=%s text=%r", kind, session, files, text[:120]
    )
    return MediaResult(session=session, files=files, text=text)


async def download_session_file(
    client: httpx.AsyncClient, session: str, file_id: str, token: str
) -> tuple[bytes, str]:
    """下载 session 内生成的文件，返回 (bytes, mime_type)。"""
    res = await client.get(
        download_url(session, file_id),
        headers={
            "Authorization": f"Bearer {token}",
            "X-Goog-User-Project": settings.gcp_project_id,
        },
        follow_redirects=True,
        timeout=DOWNLOAD_TIMEOUT,
    )
    if res.status_code != 200:
        logger.error("GE file download %s: %s", res.status_code, res.text[:500])
        raise HTTPException(
            status_code=res.status_code, detail=f"GE file download error: {res.text}"
        )
    mime = res.headers.get("content-type", "application/octet-stream").split(";")[0].strip()
    return res.content, mime
